### ISSUE TITLE
Cannot display the video sequence

### ISSUE THREAD

**Issue by jiangqb** [TuringKi/fDSST_cpp#1]
Hi @TuringKi ,
It's very nice of you to make your code open-source, but when I run the code I found that the picture displayed was always the first one, and the bounding-box was the given groundtruth of the first frame all the time. In fact, the imread() function load frames according to the order of sequence for each cycle. I'm not sure what leads to this phenomena. Any suggestion is appreciated, thank you.  :）

**Comment by TuringKi** [comment]
I am not carefully check out the runtracker.cpp..... maybe you should look at the KCF_cpp (https://github.com/joaofaro/KCFcpp)code, It's should be working, the interfaces are same.

**Comment by jiangqb** [comment]
Well...Haven't you run your code by your own? Thank your advice anyway :）

**Comment by TuringKi** [comment]
跑过啊。。。最近太忙了，可能有些更新我没有推送上去。。。。

**Comment by jiangqb** [comment]
哈哈哈，果然还是中文交流起来最爽了，我也很好奇为啥会出现这种状况，每次读取的图片的是下一视频帧，我还在每一帧上添加了显示当前帧数，帧数不断变化但是图还是第一帧的图- -；

**Comment by jiangqb** [comment]
啊啊啊，是我数据的问题。。。。我感觉日了狗- -；代码没有问题，sorry for this~
